"""Generation and lifecycle of per-WebApp launcher wrapper scripts.

A wrapper script is generated per entry only when the configured mobile and
desktop modes differ. The .desktop file's `Exec=` then points to the wrapper
instead of the browser directly. The wrapper detects the form factor at launch
time and execs the matching browser argv.

Detection signals (strong, no heuristics):
- $XDG_CURRENT_DESKTOP / $XDG_SESSION_DESKTOP contains `phosh` or `plasma-mobile`
- A FuriOS marker file exists
- $WEBAPP_FORM env var (`mobile` / `desktop`) overrides everything
"""
from __future__ import annotations

import os
import shlex
import stat
from pathlib import Path

from app_identity import APP_DATA_DIR

LAUNCHER_DIR = APP_DATA_DIR / 'launchers'

_WRAPPER_HEAD = """#!/bin/sh
# Auto-generated by WebApp Manager. Do not edit by hand —
# changes are overwritten on the next export.

case "${WEBAPP_FORM:-}" in
    mobile|desktop) FORM="$WEBAPP_FORM" ;;
    *)
        FORM=desktop
        case ":${XDG_CURRENT_DESKTOP:-}:${XDG_SESSION_DESKTOP:-}:" in
            *[Pp]hosh*|*plasma-mobile*|*Plasma-Mobile*) FORM=mobile ;;
        esac
        if [ "$FORM" = "desktop" ] && [ -f /etc/furios-release ]; then
            FORM=mobile
        fi
        ;;
esac

case "$FORM" in
    mobile)
        exec """

_WRAPPER_SEP = """
        ;;
    *)
        exec """

_WRAPPER_TAIL = """
        ;;
esac
"""


def ensure_launcher_dir() -> Path:
    LAUNCHER_DIR.mkdir(parents=True, exist_ok=True)
    return LAUNCHER_DIR


def wrapper_path_for_slug(slug: str) -> Path:
    return LAUNCHER_DIR / f'{slug}.sh'


def render_wrapper(mobile_argv: list[str], desktop_argv: list[str]) -> str:
    return (
        _WRAPPER_HEAD
        + shlex.join(mobile_argv)
        + _WRAPPER_SEP
        + shlex.join(desktop_argv)
        + _WRAPPER_TAIL
    )


def write_wrapper(slug: str, mobile_argv: list[str], desktop_argv: list[str]) -> Path:
    if not slug:
        raise ValueError('Cannot write wrapper for empty slug')
    ensure_launcher_dir()
    target = wrapper_path_for_slug(slug)
    content = render_wrapper(mobile_argv, desktop_argv)
    existing = ''
    if target.exists():
        try:
            existing = target.read_text(encoding='utf-8')
        except OSError:
            existing = ''
    if existing != content:
        target.write_text(content, encoding='utf-8')
    try:
        current_mode = target.stat().st_mode
        target.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass
    return target


def delete_wrapper(slug: str) -> bool:
    if not slug:
        return False
    target = wrapper_path_for_slug(slug)
    try:
        target.unlink()
        return True
    except FileNotFoundError:
        return False
    except OSError:
        return False


def list_wrappers() -> list[Path]:
    if not LAUNCHER_DIR.exists():
        return []
    return sorted(p for p in LAUNCHER_DIR.iterdir() if p.is_file() and p.suffix == '.sh')


def cleanup_orphaned_wrappers(active_slugs) -> list[Path]:
    """Remove wrapper scripts that no longer correspond to a known slug."""
    active = {s for s in active_slugs if s}
    removed = []
    for wrapper in list_wrappers():
        if wrapper.stem in active:
            continue
        try:
            wrapper.unlink()
            removed.append(wrapper)
        except OSError:
            pass
    return removed
